name: "Auto Label"

on:
  - pull_request_target

jobs:
  assign_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with: 
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/auto-label.yml