name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'

env:
  ACTOR: ${{ github.actor }}
  BASE_URL: cu-webring.org
  PREVIEW_PATH: preview/${{ github.actor }}/pr-${{ github.event.number }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create preview directory
        run: |
          mkdir -p ${{ env.PREVIEW_PATH }}
          rsync -av --exclude='preview' ./ ${{ env.PREVIEW_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.PREVIEW_PATH }}

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true

      - name: Generate preview URL
        id: preview-url
        run: |
          echo "PREVIEW_URL=https://${{ env.BASE_URL }}/${{ env.PREVIEW_PATH }}" >> $GITHUB_ENV

      - name: Comment on PR with preview link
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = process.env.PREVIEW_URL;
            const comment = `
              ⚡ Congrats! Your Preview deployment is ready!
      
              You can view the preview of the webring with your changes at:
              ${previewUrl}
      
              This preview will be automatically updated as you make changes to your PR.
            `.trim();
            
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
              console.log('Comment posted successfully!');
            } catch (error) {
              console.error('Failed to post comment:', error);
            }