name: PR Preview Deployment
env:
  ACTOR: ${{ github.actor }}
  BASE_URL: cu-webring.org
  PREVIEW_PATH: preview/${{ github.actor }}/pr-${{ github.event.number }}
run-name: ${{ github.actor }} is deploying a preview for PR ${{ github.event.number }}

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    # triggers a workflow if a PR modifies any of these files
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      pages: write
      # needed for deployment
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Prepare files for deployment
      - name: Prepare Files for Deployment
        run: |
          mkdir -p ${{ env.PREVIEW_PATH }}
          rsync -av --exclude='preview' ./ ${{ env.PREVIEW_PATH }}

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Deploy the root directory
          destination_dir: ${{ env.PREVIEW_PATH }}  # Unique preview path
          keep_files: true  # Keep existing files in the gh-pages branch

      # Comment on the PR with the preview link
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = 'https://${{ env.BASE_URL }}/${{ env.PREVIEW_PATH }}/';
            
            const comment = `
              ⚡ Congrats! Your Preview deployment is ready!
      
              You can view the preview of the webring with your changes at:
              ${previewUrl}
      
              This preview will be automatically updated as you make changes to your PR.
            `.trim();
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });