name: PR Preview Deployment

env:
  PREVIEW_PATH: preview/${{ github.actor }}/pr-${{ github.event.number }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare files
        run: |
          rm -rf ./preview
          mkdir -p ./${{ env.PREVIEW_PATH }}
          rsync -av --exclude='.git' --exclude='preview' ./ ./${{ env.PREVIEW_PATH }}/
          touch ./${{ env.PREVIEW_PATH}}/.nojekyll

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
        with:
          target-path: ${{ env.PREVIEW_PATH }}

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const pagesUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/${{ env.PREVIEW_PATH }}/`;
            const customUrl = `https://cu-webring.org/${{ env.PREVIEW_PATH }}/`;
            
            const comment = `
              🚀 Preview Deployed!
              
              **GitHub Pages URL:**  
              ${pagesUrl}
              
              **Custom Domain URL:**  
              ${customUrl}
              
              Allow 1-2 minutes for deployment propagation.
            `;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });