name: PR Preview Deployment
env:
  ACTOR: ${{ github.actor }}
  PREVIEW_URL: https://cu-webring/preview/${{ github.actor }}/pr-${{ github.event.number }}/
run-name: ${{ github.actor }}  is deploying a preview for PR ${{ github.event.number }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # triggers a workflow if a pr changes any of these files
    paths:
      - 'js/user_sites.js'
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
  push:
    branches:
     - main
    paths:
      - 'js/user_sites.js'
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ env.PREVIEW_URL }}
    permissions:
      pull-requests: write
      contents: read
      id-token: write
      pages: write

    steps:
      - uses: actions/checkout@v4

      # - name: Validate JSON
      #   run: bash ./.github/workflows/validate_json.sh

      - name: Deploy to GitHub Pages Preview
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            console.log("check Context:\n", JSON.stringify(github, null, 2), "\n");
            const comment = `📝 Preview deployment is ready!\n\nYou can view the preview of the webring with 
            your changes at: ${{env.PREVIEW_URL}}\n\nThis preview will be automatically updated as you make 
            changes to your PR.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });